Added new programs to learning and exercises packages
marekk1992/JavaMasterclass_Section4 pull request #7
Opened 2022-01-24 21:09 UTC by marekk1992

2022-01-25 07:09 UTC, RobertasVainickas requested changes

2022-01-25 07:09 UTC, RobertasVainickas commented on src/exercises/equalityPrinter/EqualityPrinter.java
> +        if ((number1 < 0) || (number2 < 0) || (number3 < 0)) {
Unnecessary inner braces. 
Please fix all the other places in this PR too as there are quite a lot of them

2022-01-25 07:09 UTC, RobertasVainickas commented on src/exercises/teenNumberChecker/TeenNumberChecker.java
> +        return (value1 <= 19 && value1 >= 13) || (value2 <= 19 && value2 >= 13)
You introduced isTeen method on the line 10, but don't use it here

2022-01-25 10:38 UTC, marekk1992 commented on src/exercises/equalityPrinter/EqualityPrinter.java
> +        if ((number1 < 0) || (number2 < 0) || (number3 < 0)) {
Removed inner braces from all required places.

2022-01-25 10:38 UTC, marekk1992 commented on src/exercises/teenNumberChecker/TeenNumberChecker.java
> +        return (value1 <= 19 && value1 >= 13) || (value2 <= 19 && value2 >= 13)
Added isTeen method to hasTeen method.

2022-01-25 10:45 UTC, RobertasVainickas requested changes

2022-01-25 10:45 UTC, RobertasVainickas commented on src/learning/secondsAndMinutesChallenge/SecondsAndMinutesChallenge.java
> +        if ((minutes < 0) || (seconds < 0) || (seconds > 59)) {
You left braces here

2022-01-25 10:45 UTC, RobertasVainickas commented on src/learning/methodOverloading/MethodOverloading.java
> +        if ((feet < 0) || (inches < 0) || (inches > 12)) {
And here

2022-01-25 21:33 UTC, marekk1992 commented on src/learning/secondsAndMinutesChallenge/SecondsAndMinutesChallenge.java
> +        if ((minutes < 0) || (seconds < 0) || (seconds > 59)) {
Removed

2022-01-25 21:33 UTC, marekk1992 commented on src/learning/methodOverloading/MethodOverloading.java
> +        if ((feet < 0) || (inches < 0) || (inches > 12)) {
Removed

2022-01-26 06:38 UTC, RobertasVainickas approved these changes

2022-01-27 15:52 UTC, merged